export const SITE_CONFIG = {
  siteUrl: 'https://ralhumsports.lk',
  currency: 'LKR',
  about: {
    companyName: 'Ralhum Sports',
    legalName: 'Ralhum Trading Pvt Ltd',
    tagline: "Sri Lanka's #1 Sports Equipment Distributor & Online Store",
    description:
      "Sri Lanka's #1 sports equipment distributor for 30 years. Exclusive distributor of world-renowned sports brands.",
    address: {
      street: '34A, Shruberry Garden',
      city: 'Colombo 04',
      country: 'Sri Lanka',
    },
    legacy: {
      parentCompany: 'S.M.M.Muhlar & Co',
      parentCompanyYears: '75+',
      legacyText:
        'Our parent company, S.M.M.Muhlar & Co, has been a trusted name in Sri Lankan business for over 75 years. This heritage of excellence and integrity forms the foundation of everything we do at Ralhum Sports.',
    },
    timeline: [
      {
        year: '1921',
        title: 'S.M.M.Muhlar & Co Founded',
        description:
          'Parent company established by S.M.M.Muhlar, pioneering garment accessories and consumer products',
        icon: 'Calendar',
        color: 'from-brand-secondary to-secondary-600',
      },
      {
        year: '1996',
        title: 'Ralhum Sports Established',
        description: 'Founded primarily to serve the cricket industry in Sri Lanka',
        icon: 'Trophy',
        color: 'from-brand-primary to-primary-600',
      },
      {
        year: '2000s',
        title: 'Portfolio Expansion',
        description:
          'Gradually expanded to include global brands across multiple sports categories',
        icon: 'TrendingUp',
        color: 'from-brand-accent to-warning',
      },
      {
        year: 'Present',
        title: 'Market Leadership',
        description: 'Leading sports distributing company in Sri Lanka for over 25 years',
        icon: 'Award',
        color: 'from-brand-accent to-brand-primary',
      },
    ],
    established: 1996,
    yearsOfExcellence: '30',
  },
  contact: {
    telephone: '+94114388826',
    secondaryTelephone: '+94114388825',
    phone: '+94774477633',
    email: 'vamos@ralhum.com',
    whatsapp: '+94774477633',
    whatsappUrl: 'https://wa.me/94774477633',
    supportHours: 'Mon-Fri: 10AM-6PM',
    address: {
      street: '34A, Shruberry Garden',
      city: 'Colombo 04',
      country: 'Sri Lanka',
    },
    hours: {
      monday: '9AM-6PM',
      tuesday: '9AM-6PM',
      wednesday: '9AM-6PM',
      thursday: '9AM-6PM',
      friday: '9AM-6PM',
      saturday: '9AM-6PM',
      sunday: 'Closed',
    },
  },
  social: {
    facebook: 'https://facebook.com/ralhum',
    instagram: 'https://instagram.com/ralhum_sports.sl',
  },
  branding: {
    logoText: 'RALHUM SPORTS',
    logoImage: '/logo.svg',
    companyName: 'Ralhum Sports Pvt Ltd',
    colors: {
      primary: '#FF6B35', // Orange - buttons, CTAs, links, active states
      secondary: '#3B82F6', // Dark blue-gray - headers, important text
      accent: '#F39C12', // Warm amber - highlights, badges, sale indicators
      background: '#FAFAFA', // Soft off-white - main background
      surface: '#FFFFFF', // Pure white for cards
      textPrimary: '#2D3436', // Dark charcoal - main text
      textSecondary: '#636E72', // Medium gray - secondary text
      border: '#DDD', // Light gray - borders, cards, dividers
    },
    cta: {
      shop: 'START SHOPPING',
      contact: 'CONTACT US',
      whatsapp: 'WHATSAPP US',
      getQuote: 'GET QUOTE NOW',
    },
  },
  brands: [
    {
      name: 'Gray-Nicolls',
      category: 'Cricket',
      heritage: 'Since 1855',
      tagline: "Cricket's Finest Since 1855",
      description:
        "Gray-Nicolls continues to craft the world's finest cricket equipment with over 170 years of heritage. From their Robertsbridge factory, they merge traditional craftsmanship with cutting-edge innovation, producing the 2025 Ventus and Stratos ranges alongside the legendary Classic Collection used by elite players worldwide.",
      color: 'from-[#003DA5] via-[#0052CC] to-[#1A1A1A]',
      achievements: [
        'Official England Cricket Team Supplier',
        'Trusted by legends from W.G. Grace to modern stars',
        'World-class manufacturing in Robertsbridge since 1855',
        'Pioneers of the 2025 Ventus and Stratos bat technology',
        'Grade Four English Willow specialist craftsmanship',
      ],
      products: [
        {
          name: 'Cricket Bats',
          description: 'Ventus, Stratos, GEM 2.0, Classic Collection & Ultimate series bats',
        },
        {
          name: 'Protective Gear',
          description: 'Advanced helmets, pads, gloves & protective clads',
        },
        {
          name: 'Cricket Balls',
          description: 'Match and practice balls meeting international standards',
        },
        {
          name: 'Accessories',
          description: 'Premium kit bags, stumps, training equipment & bat care essentials',
        },
      ],
      image: '/gray-nicolls.jpeg',
      slug: 'gray-nicolls',
      icon: 'Trophy',
      featured: true,
    },
    {
      name: 'Gilbert',
      category: 'Rugby',
      heritage: 'Since 1823',
      tagline: "Rugby's Global Standard",
      description:
        'Gilbert leads rugby innovation with 200+ years of excellence. Official Rugby World Cup ball supplier since 1995, now powering RWC 2025 and extending their URC partnership beyond 10 years. The revolutionary iNNOVO dual-valve technology sets the gold standard for international rugby.',
      color: 'from-[#FF3D00] via-[#FF6B47] to-[#1A1A1A]',
      achievements: [
        'Official Rugby World Cup Ball since 1995',
        'Official ball supplier for Rugby World Cup 2025',
        'URC partnership renewed until 2035+',
        'Revolutionary iNNOVO dual-valve technology pioneer',
        'Official ball for international rugby competitions globally',
      ],
      products: [
        { name: 'Rugby Balls', description: 'iNNOVO match balls, training & replica collections' },
        {
          name: 'Training Equipment',
          description: 'Professional cones, tackle bags, headguards & coaching aids',
        },
        {
          name: 'Protective Gear',
          description: 'Advanced headguards, shoulder pads & body protection',
        },
        {
          name: 'Team Accessories',
          description: 'Equipment bags, ball pumps, teamwear & training accessories',
        },
      ],
      image: '/gilbert.svg',
      slug: 'gilbert',
      icon: 'Award',
      featured: true,
    },
    {
      name: 'Grays',
      category: 'Hockey',
      heritage: 'Field Sports Excellence',
      tagline: 'Elite Hockey Performance',
      description:
        'Grays delivers Olympic-caliber hockey innovation with cutting-edge composite stick technology and comprehensive protective equipment. Their advanced engineering and performance-driven designs make them the preferred choice for international hockey athletes and national teams worldwide.',
      color: 'from-[#AEEA00] via-[#7CB342] to-[#1A1A1A]',
      achievements: [
        'Olympic standard equipment supplier',
        'Trusted by international and national hockey teams',
        'Advanced composite stick technology leader',
        'Performance-driven protective gear innovation',
        'Global field hockey equipment specialist',
      ],
      products: [
        {
          name: 'Hockey Sticks',
          description: 'Advanced composite & wooden sticks for all playing positions',
        },
        {
          name: 'Protective Equipment',
          description: 'Professional shin guards, gloves & goalkeeping gear',
        },
        {
          name: 'Hockey Balls',
          description: 'Competition and training balls for all surface types',
        },
        {
          name: 'Training Gear',
          description: 'Skill cones, portable goals & development equipment',
        },
      ],
      image: '/grays.png',
      slug: 'grays',
      icon: 'Star',
      featured: true,
    },
    {
      name: 'Babolat',
      category: 'Tennis & Badminton',
      heritage: 'Innovation Leader',
      tagline: 'Pure Performance',
      description:
        'French racquet sport innovator pioneering Aero technology and smart racquet systems. As the official partner of Roland-Garros, Babolat continues pushing boundaries with connected racquet technology and precision-engineered equipment for professional and amateur players.',
      color: 'from-[#FF3D00] via-[#FF6B47] to-[#AEEA00]',
      achievements: [
        'Official Roland-Garros partner',
        'Creator of revolutionary Aero racquet series',
        'Smart racquet technology pioneer',
        'Professional tournament equipment supplier',
        'French heritage in racquet sports innovation',
      ],
      products: [
        {
          name: 'Tennis Rackets',
          description: 'Professional tournament rackets with Aero technology',
        },
        { name: 'Badminton Rackets', description: 'Precision-engineered competitive rackets' },
        {
          name: 'Strings & Accessories',
          description: 'Performance strings, grips & maintenance tools',
        },
        {
          name: 'Court Equipment',
          description: 'Training aids, ball machines & court accessories',
        },
      ],
      image: '/babolat.svg',
      slug: 'babolat',
      icon: 'Target',
    },
    {
      name: 'Molten',
      category: 'Basketball & Volleyball',
      heritage: 'Innovation Leader',
      tagline: 'Official Game Standard',
      description:
        'Molten leads basketball and volleyball innovation as the official supplier to FIBA, Olympic Games, and world championships. Their cutting-edge ball technology powered Paris 2024 Olympics and continues setting the standard for professional leagues globally.',
      color: 'from-[#FFD700] via-[#FFA500] to-[#1A1A1A]',
      achievements: [
        'Official Paris 2024 Olympics supplier',
        'FIBA World Championship official ball',
        "NCAA men's and women's championships supplier",
        'USA Volleyball official ball provider',
        'Global professional league standard',
      ],
      products: [
        {
          name: 'Basketballs',
          description: 'Olympic-grade indoor/outdoor balls for all competition levels',
        },
        { name: 'Volleyballs', description: 'Championship and recreational volleyballs' },
        {
          name: 'Training Equipment',
          description: 'Professional ball carts, pumps & training accessories',
        },
        {
          name: 'Court Accessories',
          description: 'Electronic scoreboards, nets & court equipment',
        },
      ],
      image: '/molten.png',
      slug: 'molten',
      icon: 'Target',
      featured: true,
    },
    {
      name: 'Pugg',
      category: 'Football & Training',
      heritage: 'Patented in 1994, USA',
      tagline: 'The Original Pop-Up',
      specialty: 'Pop-Up Goals',
      description:
        'The original 1994 patented steel-wire pop-up goal system, revolutionizing portable training equipment. Pugg goals remain the gold standard for professional coaches worldwide, offering unmatched portability and durability for training sessions and skill development.',
      color: 'from-[#F9D923] to-[#1A1A1A]',
      achievements: [
        'Original 1994 pop-up goal patent holder',
        'Professional coaching essential worldwide',
        'Portable training revolution pioneer',
        'Steel-wire construction durability leader',
        'Quick-setup training solution standard',
      ],
      image: '/pugg.png',
      slug: 'pugg',
      icon: 'Package',
      products: [
        {
          name: 'Pop-Up Goals',
          description: 'Original portable training goals for football and futsal',
        },
        { name: 'Training Sets', description: 'Complete goal systems with carry bags' },
        { name: 'Replacement Parts', description: 'Spare nets, pegs & maintenance components' },
      ],
    },
    {
      name: 'Aero',
      category: 'Cricket',
      heritage: 'Late 1990s, New Zealand',
      specialty: 'Protective Gear',
      tagline: 'Safety First',
      description:
        "New Zealand cricket safety specialists delivering cutting-edge protective technology since the late 1990s. Aero's impact-tested pads withstand 100+ mph deliveries, providing uncompromising protection trusted by professional cricketers worldwide.",
      color: 'from-[#00C853] to-[#1A1A1A]',
      achievements: [
        '100+ mph impact certification',
        'Professional player safety standard',
        'New Zealand engineering excellence',
        'Cricket protection innovation leader',
        'Trusted by international cricketers',
      ],
      image: '/placeholder.svg',
      slug: 'aero',
      icon: 'Award',
      products: [
        {
          name: 'Protective Pads',
          description: 'High-impact cricket batting and wicket-keeping pads',
        },
        { name: 'Thigh Guards', description: 'Lightweight impact-resistant thigh protection' },
        { name: 'Arm Guards', description: 'Flexible forearm and elbow protection systems' },
      ],
    },
    {
      name: 'Leverage',
      category: 'Cricket',
      heritage: 'Cricket Tech Pioneer',
      specialty: 'Bowling Machines',
      tagline: 'Practice Perfection',
      description:
        'Revolutionary bowling machine technology delivering swing, spin, and pace up to 160 km/h. Leverage transforms cricket training with affordable, advanced machines that provide consistent delivery for players and coaches seeking performance excellence.',
      color: 'from-[#FF6F00] to-[#1A1A1A]',
      achievements: [
        'Training technology revolution',
        '160 km/h delivery capability',
        'Swing, spin, and pace mastery',
        'Affordable advanced cricket training',
        'Professional coach preferred choice',
      ],
      image: '/leverage.png',
      slug: 'leverage',
      icon: 'TrendingUp',
      products: [
        {
          name: 'Bowling Machines',
          description: 'Advanced swing, spin, and pace delivery systems',
        },
        {
          name: 'Machine Accessories',
          description: 'Ball feeders, remote controls & maintenance kits',
        },
        { name: 'Training Balls', description: 'Specialized machine-compatible practice balls' },
      ],
    },
    {
      name: 'Ashaway',
      category: 'Badminton & Squash',
      heritage: 'Founded 1824, USA',
      specialty: 'Badminton & Squash',
      tagline: 'String Excellence',
      description:
        "American string craftsmanship since 1824, delivering performance strings for badminton, squash, and tennis. Ashaway's precision-engineered strings provide the perfect balance of power, control, and durability for competitive players worldwide.",
      color: 'from-[#C62828] to-[#1A1A1A]',
      achievements: [
        'String innovation since 1824',
        'Made in USA quality craftsmanship',
        'Global competitive player choice',
        'Precision-engineered performance strings',
        'Multi-sport string expertise',
      ],
      image: '/ashaway.jpeg',
      slug: 'ashaway',
      icon: 'Star',
      products: [
        {
          name: 'Badminton Strings',
          description: 'High-performance competitive badminton strings',
        },
        { name: 'Squash Strings', description: 'Precision squash strings for power and control' },
        {
          name: 'Tennis Strings',
          description: 'Professional tennis strings for all playing styles',
        },
        {
          name: 'String Accessories',
          description: 'Stringing tools, grips & maintenance equipment',
        },
      ],
    },
    {
      name: 'Fusion',
      category: 'Multi-Sport Training',
      heritage: 'Multi-Sport Focus',
      specialty: 'Training Equipment',
      tagline: 'Train Like a Pro',
      description:
        'Comprehensive multi-sport training solutions built for durability and performance. Fusion delivers coach-approved equipment across multiple disciplines, providing athletes with versatile training tools that enhance skills and maximize potential.',
      color: 'from-[#7B1FA2] to-[#1A1A1A]',
      achievements: [
        'Multi-sport training expertise',
        'Coach-approved equipment standards',
        'Durable performance construction',
        'Versatile training solutions',
        'Athlete development focused',
      ],
      image: '/fusion.jpg',
      slug: 'fusion',
      icon: 'Globe',
      products: [
        { name: 'Training Equipment', description: 'Multi-sport training gear and accessories' },
        {
          name: 'Agility Tools',
          description: 'Cones, ladders, hurdles & speed training equipment',
        },
        {
          name: 'Strength Training',
          description: 'Resistance bands, weights & functional training tools',
        },
        { name: 'Team Accessories', description: 'Equipment bags, storage solutions & team gear' },
      ],
    },
  ],
  stats: [
    { number: '30', label: 'Years of Excellence', color: '#3B82F6' },
    { number: '75+', label: 'Years Parent Company Heritage', color: '#FF6B35' },
    { number: '1000+', label: 'Schools & Clubs Served', color: '#F39C12' },
    { number: '#1', label: 'Sports Distributor in Sri Lanka', color: '#00B894' },
  ],
  whatsapp: {
    number: '94774477633',
    message: "Hello Ralhum Sports! I'm interested in your sports equipment. Please contact me.",
    reportMessage: 'Hello! I need to report a product verification issue. SKU: ',
  },

  SRI_LANKAN_CITIES: [
    { name: 'Colombo', postalCode: '00100', province: 'Western Province' },
    { name: 'Dehiwala', postalCode: '10350', province: 'Western Province' },
    { name: 'Mount Lavinia', postalCode: '10370', province: 'Western Province' },
    { name: 'Maharagama', postalCode: '10280', province: 'Western Province' },
    { name: 'Kotte', postalCode: '10100', province: 'Western Province' },
    { name: 'Nugegoda', postalCode: '10250', province: 'Western Province' },
    { name: 'Battaramulla', postalCode: '10120', province: 'Western Province' },
    { name: 'Rajagiriya', postalCode: '10107', province: 'Western Province' },
    { name: 'Malabe', postalCode: '10115', province: 'Western Province' },
    { name: 'Pannipitiya', postalCode: '10230', province: 'Western Province' },
    { name: 'Moratuwa', postalCode: '10400', province: 'Western Province' },
    { name: 'Panadura', postalCode: '12500', province: 'Western Province' },
    { name: 'Kalutara', postalCode: '12000', province: 'Western Province' },
    { name: 'Negombo', postalCode: '11500', province: 'Western Province' },
    { name: 'Gampaha', postalCode: '11000', province: 'Western Province' },
    { name: 'Kelaniya', postalCode: '11300', province: 'Western Province' },
    { name: 'Wattala', postalCode: '11300', province: 'Western Province' },
    { name: 'Ja-Ela', postalCode: '11350', province: 'Western Province' },
    { name: 'Katunayake', postalCode: '11450', province: 'Western Province' },
    { name: 'Seeduwa', postalCode: '11410', province: 'Western Province' },
    { name: 'Homagama', postalCode: '10200', province: 'Western Province' },
    { name: 'Kaduwela', postalCode: '10640', province: 'Western Province' },
    { name: 'Angoda', postalCode: '10620', province: 'Western Province' },
    { name: 'Piliyandala', postalCode: '10300', province: 'Western Province' },
    { name: 'Kesbewa', postalCode: '10300', province: 'Western Province' },
    { name: 'Ratmalana', postalCode: '10390', province: 'Western Province' },
    { name: 'Bellanwila', postalCode: '10290', province: 'Western Province' },
    { name: 'Borelasgamuwa', postalCode: '10290', province: 'Western Province' },
    { name: 'Talawathugoda', postalCode: '10116', province: 'Western Province' },
    { name: 'Athurugiriya', postalCode: '10150', province: 'Western Province' },
    { name: 'Kiribathgoda', postalCode: '11600', province: 'Western Province' },
    { name: 'Ragama', postalCode: '11010', province: 'Western Province' },
    { name: 'Delgoda', postalCode: '11700', province: 'Western Province' },
    { name: 'Minuwangoda', postalCode: '11550', province: 'Western Province' },
    { name: 'Divulapitiya', postalCode: '11250', province: 'Western Province' },
    { name: 'Nittambuwa', postalCode: '11880', province: 'Western Province' },
    { name: 'Veyangoda', postalCode: '11870', province: 'Western Province' },
    { name: 'Mirigama', postalCode: '11200', province: 'Western Province' },
    { name: 'Dompe', postalCode: '11680', province: 'Western Province' },
    { name: 'Hanwella', postalCode: '10650', province: 'Western Province' },
    { name: 'Avissawella', postalCode: '10700', province: 'Western Province' },
    { name: 'Padukka', postalCode: '10500', province: 'Western Province' },

    // Central Province
    { name: 'Kandy', postalCode: '20000', province: 'Central Province' },
    { name: 'Matale', postalCode: '21000', province: 'Central Province' },
    { name: 'Nuwara Eliya', postalCode: '22200', province: 'Central Province' },
    { name: 'Gampola', postalCode: '20500', province: 'Central Province' },
    { name: 'Nawalapitiya', postalCode: '20650', province: 'Central Province' },
    { name: 'Hatton', postalCode: '22000', province: 'Central Province' },
    { name: 'Dimbula', postalCode: '22100', province: 'Central Province' },
    { name: 'Nallathanni', postalCode: '22070', province: 'Central Province' },
    { name: 'Talawakelle', postalCode: '22030', province: 'Central Province' },
    { name: 'Lindula', postalCode: '22060', province: 'Central Province' },
    { name: 'Peradeniya', postalCode: '20400', province: 'Central Province' },
    { name: 'Akurana', postalCode: '20850', province: 'Central Province' },
    { name: 'Katugastota', postalCode: '20800', province: 'Central Province' },
    { name: 'Wattegama', postalCode: '20250', province: 'Central Province' },
    { name: 'Kadugannawa', postalCode: '20300', province: 'Central Province' },
    { name: 'Kegalle', postalCode: '71000', province: 'Sabaragamuwa Province' },
    { name: 'Mawanella', postalCode: '71500', province: 'Sabaragamuwa Province' },
    { name: 'Rambukkana', postalCode: '71100', province: 'Sabaragamuwa Province' },
    { name: 'Galigamuwa', postalCode: '71350', province: 'Sabaragamuwa Province' },
    { name: 'Warakapola', postalCode: '71600', province: 'Sabaragamuwa Province' },
    { name: 'Ratnapura', postalCode: '70000', province: 'Sabaragamuwa Province' },
    { name: 'Embilipitiya', postalCode: '70200', province: 'Sabaragamuwa Province' },
    { name: 'Balangoda', postalCode: '70100', province: 'Sabaragamuwa Province' },
    { name: 'Pelmadulla', postalCode: '70070', province: 'Sabaragamuwa Province' },
    { name: 'Kuruwita', postalCode: '70400', province: 'Sabaragamuwa Province' },
    { name: 'Eheliyagoda', postalCode: '70600', province: 'Sabaragamuwa Province' },
    { name: 'Kiriella', postalCode: '70480', province: 'Sabaragamuwa Province' },

    // Southern Province
    { name: 'Galle', postalCode: '80000', province: 'Southern Province' },
    { name: 'Matara', postalCode: '81000', province: 'Southern Province' },
    { name: 'Hambantota', postalCode: '82000', province: 'Southern Province' },
    { name: 'Tangalle', postalCode: '82200', province: 'Southern Province' },
    { name: 'Weligama', postalCode: '81700', province: 'Southern Province' },
    { name: 'Mirissa', postalCode: '81740', province: 'Southern Province' },
    { name: 'Hikkaduwa', postalCode: '80240', province: 'Southern Province' },
    { name: 'Unawatuna', postalCode: '80600', province: 'Southern Province' },
    { name: 'Bentota', postalCode: '80500', province: 'Southern Province' },
    { name: 'Beruwala', postalCode: '12070', province: 'Western Province' },
    { name: 'Aluthgama', postalCode: '12080', province: 'Western Province' },
    { name: 'Ambalangoda', postalCode: '80300', province: 'Southern Province' },
    { name: 'Elpitiya', postalCode: '80400', province: 'Southern Province' },
    { name: 'Akuressa', postalCode: '81400', province: 'Southern Province' },
    { name: 'Deniyaya', postalCode: '81500', province: 'Southern Province' },
    { name: 'Hakmana', postalCode: '81200', province: 'Southern Province' },
    { name: 'Kamburupitiya', postalCode: '81100', province: 'Southern Province' },
    { name: 'Devinuwara', postalCode: '81200', province: 'Southern Province' },
    { name: 'Tissamaharama', postalCode: '82600', province: 'Southern Province' },
    { name: 'Kataragama', postalCode: '91400', province: 'Uva Province' },
    { name: 'Ambalantota', postalCode: '82100', province: 'Southern Province' },
    { name: 'Beliatta', postalCode: '82400', province: 'Southern Province' },
    { name: 'Weeraketiya', postalCode: '82500', province: 'Southern Province' },
    { name: 'Suriyawewa', postalCode: '82020', province: 'Southern Province' },

    // Northern Province
    { name: 'Jaffna', postalCode: '40000', province: 'Northern Province' },
    { name: 'Kilinochchi', postalCode: '44000', province: 'Northern Province' },
    { name: 'Mannar', postalCode: '41000', province: 'Northern Province' },
    { name: 'Mullaitivu', postalCode: '42000', province: 'Northern Province' },
    { name: 'Vavuniya', postalCode: '43000', province: 'Northern Province' },
    { name: 'Point Pedro', postalCode: '40300', province: 'Northern Province' },
    { name: 'Chavakacheri', postalCode: '40400', province: 'Northern Province' },
    { name: 'Valvettithurai', postalCode: '40350', province: 'Northern Province' },
    { name: 'Nallur', postalCode: '40100', province: 'Northern Province' },
    { name: 'Chunnakam', postalCode: '40420', province: 'Northern Province' },
    { name: 'Tellippalai', postalCode: '40360', province: 'Northern Province' },
    { name: 'Kodikamam', postalCode: '40350', province: 'Northern Province' },
    { name: 'Karainagar', postalCode: '40480', province: 'Northern Province' },
    { name: 'Kayts', postalCode: '40440', province: 'Northern Province' },
    { name: 'Delft', postalCode: '40490', province: 'Northern Province' },
    { name: 'Nedunkeni', postalCode: '43006', province: 'Northern Province' },
    { name: 'Cheddikulam', postalCode: '43008', province: 'Northern Province' },
    { name: 'Omanthai', postalCode: '43014', province: 'Northern Province' },
    { name: 'Puliyankulam', postalCode: '43300', province: 'Northern Province' },
    { name: 'Kandavalai', postalCode: '44200', province: 'Northern Province' },
    { name: 'Pallai', postalCode: '44300', province: 'Northern Province' },
    { name: 'Paranthan', postalCode: '44006', province: 'Northern Province' },
    { name: 'Elephant Pass', postalCode: '44100', province: 'Northern Province' },
    { name: 'Pudukudiyiruppu', postalCode: '42300', province: 'Northern Province' },
    { name: 'Oddusuddan', postalCode: '42100', province: 'Northern Province' },
    { name: 'Maritimepattu', postalCode: '42200', province: 'Northern Province' },
    { name: 'Manthai West', postalCode: '41300', province: 'Northern Province' },
    { name: 'Musali', postalCode: '41200', province: 'Northern Province' },
    { name: 'Nanattan', postalCode: '41400', province: 'Northern Province' },
    { name: 'Madhu', postalCode: '41500', province: 'Northern Province' },

    // Eastern Province
    { name: 'Batticaloa', postalCode: '30000', province: 'Eastern Province' },
    { name: 'Ampara', postalCode: '32000', province: 'Eastern Province' },
    { name: 'Trincomalee', postalCode: '31000', province: 'Eastern Province' },
    { name: 'Kalmunai', postalCode: '32300', province: 'Eastern Province' },
    { name: 'Akkaraipattu', postalCode: '32400', province: 'Eastern Province' },
    { name: 'Sammanthurai', postalCode: '32200', province: 'Eastern Province' },
    { name: 'Pottuvil', postalCode: '32500', province: 'Eastern Province' },
    { name: 'Arugam Bay', postalCode: '32500', province: 'Eastern Province' },
    { name: 'Kattankudy', postalCode: '30100', province: 'Eastern Province' },
    { name: 'Eravur', postalCode: '30200', province: 'Eastern Province' },
    { name: 'Valaichchenai', postalCode: '30400', province: 'Eastern Province' },
    { name: 'Chenkaladi', postalCode: '30350', province: 'Eastern Province' },
    { name: 'Passikudah', postalCode: '30410', province: 'Eastern Province' },
    { name: 'Kalkudah', postalCode: '30420', province: 'Eastern Province' },
    { name: 'Vakarai', postalCode: '30450', province: 'Eastern Province' },
    { name: 'Nilaveli', postalCode: '31010', province: 'Eastern Province' },
    { name: 'Uppuveli', postalCode: '31015', province: 'Eastern Province' },
    { name: 'Kinniya', postalCode: '31100', province: 'Eastern Province' },
    { name: 'Mutur', postalCode: '31200', province: 'Eastern Province' },
    { name: 'Kuchchaveli', postalCode: '31014', province: 'Eastern Province' },
    { name: 'Kantale', postalCode: '31300', province: 'Eastern Province' },
    { name: 'Seruvila', postalCode: '31400', province: 'Eastern Province' },
    { name: 'Gomarankadawala', postalCode: '31500', province: 'Eastern Province' },
    { name: 'Somawathiya', postalCode: '31600', province: 'Eastern Province' },
    { name: 'Maha Oya', postalCode: '32100', province: 'Eastern Province' },
    { name: 'Uhana', postalCode: '32060', province: 'Eastern Province' },
    { name: 'Damana', postalCode: '32070', province: 'Eastern Province' },
    { name: 'Mahaoya', postalCode: '32100', province: 'Eastern Province' },
    { name: 'Dehiattakandiya', postalCode: '32150', province: 'Eastern Province' },
    { name: 'Navithanveli', postalCode: '32180', province: 'Eastern Province' },
    { name: 'Padiyathalawa', postalCode: '32300', province: 'Eastern Province' },
    { name: 'Lahugala', postalCode: '32350', province: 'Eastern Province' },
    { name: 'Sainthamaruthu', postalCode: '32280', province: 'Eastern Province' },
    { name: 'Ninthavur', postalCode: '32340', province: 'Eastern Province' },
    { name: 'Addalachchenai', postalCode: '32350', province: 'Eastern Province' },
    { name: 'Thirukkovil', postalCode: '32420', province: 'Eastern Province' },
    { name: 'Komari', postalCode: '32430', province: 'Eastern Province' },
    { name: 'Panama', postalCode: '32508', province: 'Eastern Province' },
    { name: 'Okanda', postalCode: '32512', province: 'Eastern Province' },

    // North Western Province
    { name: 'Kurunegala', postalCode: '60000', province: 'North Western Province' },
    { name: 'Puttalam', postalCode: '61300', province: 'North Western Province' },
    { name: 'Chilaw', postalCode: '61000', province: 'North Western Province' },
    { name: 'Narammala', postalCode: '60400', province: 'North Western Province' },
    { name: 'Wariyapola', postalCode: '60700', province: 'North Western Province' },
    { name: 'Pannala', postalCode: '60170', province: 'North Western Province' },
    { name: 'Kuliyapitiya', postalCode: '60200', province: 'North Western Province' },
    { name: 'Dambadeniya', postalCode: '60100', province: 'North Western Province' },
    { name: 'Giriulla', postalCode: '60140', province: 'North Western Province' },
    { name: 'Polgahawela', postalCode: '60300', province: 'North Western Province' },
    { name: 'Bingiriya', postalCode: '60450', province: 'North Western Province' },
    { name: 'Nikaweratiya', postalCode: '60470', province: 'North Western Province' },
    { name: 'Hettipola', postalCode: '60400', province: 'North Western Province' },
    { name: 'Mawathagama', postalCode: '60500', province: 'North Western Province' },
    { name: 'Melsiripura', postalCode: '60570', province: 'North Western Province' },
    { name: 'Ibbagamuwa', postalCode: '60500', province: 'North Western Province' },
    { name: 'Alawwa', postalCode: '60280', province: 'North Western Province' },
    { name: 'Kobeigane', postalCode: '60310', province: 'North Western Province' },
    { name: 'Maho', postalCode: '60600', province: 'North Western Province' },
    { name: 'Galgamuwa', postalCode: '60700', province: 'North Western Province' },
    { name: 'Ambanpola', postalCode: '60750', province: 'North Western Province' },
    { name: 'Ehetuwewa', postalCode: '60770', province: 'North Western Province' },
    { name: 'Polpithigama', postalCode: '60600', province: 'North Western Province' },
    { name: 'Wellawa', postalCode: '60490', province: 'North Western Province' },
    { name: 'Wennappuwa', postalCode: '61170', province: 'North Western Province' },
    { name: 'Nattandiya', postalCode: '61100', province: 'North Western Province' },
    { name: 'Mahawewa', postalCode: '61130', province: 'North Western Province' },
    { name: 'Madampe', postalCode: '61200', province: 'North Western Province' },
    { name: 'Udappuwa', postalCode: '61006', province: 'North Western Province' },
    { name: 'Bangadeniya', postalCode: '61008', province: 'North Western Province' },
    { name: 'Thalawila', postalCode: '61010', province: 'North Western Province' },
    { name: 'Kalpitiya', postalCode: '61360', province: 'North Western Province' },
    { name: 'Norochcholai', postalCode: '61370', province: 'North Western Province' },
    { name: 'Mundel', postalCode: '61350', province: 'North Western Province' },
    { name: 'Anamaduwa', postalCode: '61500', province: 'North Western Province' },
    { name: 'Karuwalagaswewa', postalCode: '61550', province: 'North Western Province' },
    { name: 'Nawagattegama', postalCode: '61040', province: 'North Western Province' },
    { name: 'Pallama', postalCode: '61070', province: 'North Western Province' },
    { name: 'Battuluoya', postalCode: '61080', province: 'North Western Province' },
    { name: 'Mahakumbukkadawala', postalCode: '61230', province: 'North Western Province' },
    { name: 'Eluwankulama', postalCode: '61240', province: 'North Western Province' },
    { name: 'Madurankuliya', postalCode: '61250', province: 'North Western Province' },
    { name: 'Arachchikattuwa', postalCode: '61260', province: 'North Western Province' },
    { name: 'Kandakuliya', postalCode: '61270', province: 'North Western Province' },
    { name: 'Palavi', postalCode: '61280', province: 'North Western Province' },
    { name: 'Dalupotha', postalCode: '61290', province: 'North Western Province' },
    { name: 'Kattampitiya', postalCode: '61292', province: 'North Western Province' },
    { name: 'Kudawa', postalCode: '61400', province: 'North Western Province' },
    {
      name: 'Puttalam Cement Corporation',
      postalCode: '61450',
      province: 'North Western Province',
    },
    { name: 'Aruwakkalu', postalCode: '61470', province: 'North Western Province' },
    { name: 'Wilpattu', postalCode: '61480', province: 'North Western Province' },
    { name: 'Pomparippen', postalCode: '61484', province: 'North Western Province' },
    { name: 'Marichchukkaddi', postalCode: '61490', province: 'North Western Province' },

    // North Central Province
    { name: 'Anuradhapura', postalCode: '50000', province: 'North Central Province' },
    { name: 'Polonnaruwa', postalCode: '51000', province: 'North Central Province' },
    { name: 'Kekirawa', postalCode: '50100', province: 'North Central Province' },
    { name: 'Thambuttegama', postalCode: '50200', province: 'North Central Province' },
    { name: 'Eppawala', postalCode: '50300', province: 'North Central Province' },
    { name: 'Galenbindunuwewa', postalCode: '50400', province: 'North Central Province' },
    { name: 'Mihintale', postalCode: '50500', province: 'North Central Province' },
    { name: 'Nochchiyagama', postalCode: '50550', province: 'North Central Province' },
    { name: 'Talawa', postalCode: '50230', province: 'North Central Province' },
    { name: 'Medawachchiya', postalCode: '50500', province: 'North Central Province' },
    { name: 'Padaviya', postalCode: '50600', province: 'North Central Province' },
    { name: 'Rambewa', postalCode: '50650', province: 'North Central Province' },
    { name: 'Kebithigollewa', postalCode: '50700', province: 'North Central Province' },
    { name: 'Maradankadawala', postalCode: '50750', province: 'North Central Province' },
    { name: 'Horowpothana', postalCode: '50800', province: 'North Central Province' },
    { name: 'Kahatagasdigiliya', postalCode: '50850', province: 'North Central Province' },
    { name: 'Rajanganaya', postalCode: '50900', province: 'North Central Province' },
    { name: 'Palagala', postalCode: '50950', province: 'North Central Province' },
    { name: 'Galnewa', postalCode: '50180', province: 'North Central Province' },
    { name: 'Thirappane', postalCode: '50190', province: 'North Central Province' },
    { name: 'Bulnewa', postalCode: '50240', province: 'North Central Province' },
    { name: 'Karadikullam', postalCode: '50250', province: 'North Central Province' },
    { name: 'Nachchaduwa', postalCode: '50260', province: 'North Central Province' },
    { name: 'Ipalogama', postalCode: '50270', province: 'North Central Province' },
    { name: 'Palugaswewa', postalCode: '50280', province: 'North Central Province' },
    { name: 'Puliyankulama', postalCode: '50290', province: 'North Central Province' },
    { name: 'Nuwaragam Palatha Central', postalCode: '50350', province: 'North Central Province' },
    { name: 'Nuwaragam Palatha East', postalCode: '50360', province: 'North Central Province' },
    { name: 'Tirappane', postalCode: '50370', province: 'North Central Province' },
    { name: 'Galkadawala', postalCode: '50380', province: 'North Central Province' },
    { name: 'Rampura', postalCode: '50390', province: 'North Central Province' },
    { name: 'Kalawewa', postalCode: '50450', province: 'North Central Province' },
    { name: 'Madatugama', postalCode: '50460', province: 'North Central Province' },
    { name: 'Thantirimale', postalCode: '50470', province: 'North Central Province' },
    { name: 'Yakawewa', postalCode: '50480', province: 'North Central Province' },
    { name: 'Kapugallawa', postalCode: '50520', province: 'North Central Province' },
    { name: 'Mahailluppallama', postalCode: '50560', province: 'North Central Province' },
    { name: 'Karuwalagaswewa', postalCode: '50570', province: 'North Central Province' },
    { name: 'Galkiriyagama', postalCode: '50580', province: 'North Central Province' },
    { name: 'Nawagattegama', postalCode: '50590', province: 'North Central Province' },
    { name: 'Hingurakgoda', postalCode: '51100', province: 'North Central Province' },
    { name: 'Medirigiriya', postalCode: '51200', province: 'North Central Province' },
    { name: 'Minneriya', postalCode: '51300', province: 'North Central Province' },
    { name: 'Habarana', postalCode: '51400', province: 'North Central Province' },
    { name: 'Dimbulagala', postalCode: '51500', province: 'North Central Province' },
    { name: 'Manampitiya', postalCode: '51600', province: 'North Central Province' },
    { name: 'Welikanda', postalCode: '51700', province: 'North Central Province' },
    { name: 'Lankapura', postalCode: '51800', province: 'North Central Province' },
    { name: 'Aralaganwila', postalCode: '51060', province: 'North Central Province' },
    { name: 'Bakamuna', postalCode: '51070', province: 'North Central Province' },
    { name: 'Bendiyawewa', postalCode: '51080', province: 'North Central Province' },
    { name: 'Jayanthipura', postalCode: '51120', province: 'North Central Province' },
    { name: 'Elahera', postalCode: '51130', province: 'North Central Province' },
    { name: 'Thamankaduwa', postalCode: '51140', province: 'North Central Province' },
    { name: 'Dambulla', postalCode: '21100', province: 'Central Province' },
    { name: 'Sigiriya', postalCode: '21120', province: 'Central Province' },
    { name: 'Galewela', postalCode: '21200', province: 'Central Province' },
    { name: 'Naula', postalCode: '21400', province: 'Central Province' },
    { name: 'Pallepola', postalCode: '21500', province: 'Central Province' },
    { name: 'Ukuwela', postalCode: '21600', province: 'Central Province' },
    { name: 'Laggala', postalCode: '21700', province: 'Central Province' },
    { name: 'Rattota', postalCode: '21800', province: 'Central Province' },
    { name: 'Yatawatta', postalCode: '21900', province: 'Central Province' },
    { name: 'Wilgamuwa', postalCode: '20900', province: 'Central Province' },

    // Uva Province
    { name: 'Badulla', postalCode: '90000', province: 'Uva Province' },
    { name: 'Monaragala', postalCode: '91000', province: 'Uva Province' },
    { name: 'Bandarawela', postalCode: '90100', province: 'Uva Province' },
    { name: 'Ella', postalCode: '90090', province: 'Uva Province' },
    { name: 'Haputale', postalCode: '90160', province: 'Uva Province' },
    { name: 'Welimada', postalCode: '90200', province: 'Uva Province' },
    { name: 'Passara', postalCode: '90500', province: 'Uva Province' },
    { name: 'Mahiyanganaya', postalCode: '90700', province: 'Uva Province' },
    { name: 'Diyatalawa', postalCode: '90150', province: 'Uva Province' },
    { name: 'Hali-Ela', postalCode: '90060', province: 'Uva Province' },
    { name: 'Demodara', postalCode: '90080', province: 'Uva Province' },
    { name: 'Namunukula', postalCode: '90130', province: 'Uva Province' },
    { name: 'Poonagala', postalCode: '90140', province: 'Uva Province' },
    { name: 'Koslanda', postalCode: '90170', province: 'Uva Province' },
    { name: 'Lunugala', postalCode: '90180', province: 'Uva Province' },
    { name: 'Meegahakiwula', postalCode: '90190', province: 'Uva Province' },
    { name: 'Rideegama', postalCode: '90210', province: 'Uva Province' },
    { name: 'Soranathota', postalCode: '90220', province: 'Uva Province' },
    { name: 'Uva Paranagama', postalCode: '90230', province: 'Uva Province' },
    { name: 'Kandaketiya', postalCode: '90240', province: 'Uva Province' },
    { name: 'Haldummulla', postalCode: '90250', province: 'Uva Province' },
    { name: 'Bogahawewa', postalCode: '90260', province: 'Uva Province' },
    { name: 'Spring Valley', postalCode: '90270', province: 'Uva Province' },
    { name: 'Boralanda', postalCode: '90280', province: 'Uva Province' },
    { name: 'Ella Gap', postalCode: '90090', province: 'Uva Province' },
    { name: 'Keppetipola', postalCode: '90300', province: 'Uva Province' },
    { name: 'Beragala', postalCode: '90310', province: 'Uva Province' },
    { name: 'Ambagasdowa', postalCode: '90320', province: 'Uva Province' },
    { name: 'Weligatta', postalCode: '90330', province: 'Uva Province' },
    { name: 'Heeloya', postalCode: '90340', province: 'Uva Province' },
    { name: 'Rathkarawwa', postalCode: '90350', province: 'Uva Province' },
    { name: 'Miriyabedda', postalCode: '90360', province: 'Uva Province' },
    { name: 'Girandurukotte', postalCode: '90370', province: 'Uva Province' },
    { name: 'Madulsima', postalCode: '90380', province: 'Uva Province' },
    { name: 'Lunugala', postalCode: '90390', province: 'Uva Province' },
    { name: 'Rikillagaskada', postalCode: '90400', province: 'Uva Province' },
    { name: 'Kandepuhulpola', postalCode: '90410', province: 'Uva Province' },
    { name: 'Gampaha', postalCode: '90420', province: 'Uva Province' },
    { name: 'Thambiluvil', postalCode: '90430', province: 'Uva Province' },
    { name: 'Paranagama', postalCode: '90440', province: 'Uva Province' },
    { name: 'Wiyaluwa', postalCode: '90450', province: 'Uva Province' },
    { name: 'Daraniyagala', postalCode: '90460', province: 'Uva Province' },
    { name: 'Kataragama', postalCode: '91400', province: 'Uva Province' },
    { name: 'Buttala', postalCode: '91100', province: 'Uva Province' },
    { name: 'Wellawaya', postalCode: '91200', province: 'Uva Province' },
    { name: 'Thanamalwila', postalCode: '91300', province: 'Uva Province' },
    { name: 'Badalkumbura', postalCode: '91500', province: 'Uva Province' },
    { name: 'Medagama', postalCode: '91600', province: 'Uva Province' },
    { name: 'Sevanagala', postalCode: '91700', province: 'Uva Province' },
    { name: 'Madulla', postalCode: '91800', province: 'Uva Province' },
    { name: 'Bibile', postalCode: '91900', province: 'Uva Province' },
    { name: 'Moneragala', postalCode: '91000', province: 'Uva Province' },
    { name: 'Siyambalanduwa', postalCode: '91050', province: 'Uva Province' },
    { name: 'Madampe', postalCode: '91080', province: 'Uva Province' },
    { name: 'Hulandawa', postalCode: '91120', province: 'Uva Province' },
    { name: 'Lahugala', postalCode: '91140', province: 'Uva Province' },
    { name: 'Galoya', postalCode: '91160', province: 'Uva Province' },
    { name: 'Kandaudakanda', postalCode: '91180', province: 'Uva Province' },
    { name: 'Rathnapura', postalCode: '91220', province: 'Uva Province' },
    { name: 'Okkampitiya', postalCode: '91240', province: 'Uva Province' },
    { name: 'Polgahawela', postalCode: '91260', province: 'Uva Province' },
    { name: 'Hidellana', postalCode: '91280', province: 'Uva Province' },
    { name: 'Uraniya', postalCode: '91320', province: 'Uva Province' },
    { name: 'Maligawila', postalCode: '91340', province: 'Uva Province' },
    { name: 'Obbegoda', postalCode: '91360', province: 'Uva Province' },
    { name: 'Yudaganawa', postalCode: '91380', province: 'Uva Province' },
    { name: 'Kumbukkana', postalCode: '91420', province: 'Uva Province' },
    { name: 'Kirinda', postalCode: '91440', province: 'Uva Province' },
    { name: 'Debarawewa', postalCode: '91460', province: 'Uva Province' },
    { name: 'Ranna', postalCode: '91480', province: 'Uva Province' },
    { name: 'Palatupana', postalCode: '91500', province: 'Uva Province' },
    { name: 'Tissamaharama', postalCode: '82600', province: 'Southern Province' },
    { name: 'Yala', postalCode: '91520', province: 'Uva Province' },
    { name: 'Katagamuwa', postalCode: '91540', province: 'Uva Province' },
    { name: 'Patanangala', postalCode: '91560', province: 'Uva Province' },
    { name: 'Bundala', postalCode: '91580', province: 'Uva Province' },
    { name: 'Lunama', postalCode: '91610', province: 'Uva Province' },
    { name: 'Weligepola', postalCode: '91630', province: 'Uva Province' },
    { name: 'Rotumba', postalCode: '91650', province: 'Uva Province' },
    { name: 'Kachchigala', postalCode: '91670', province: 'Uva Province' },
    { name: 'Kumana', postalCode: '91690', province: 'Uva Province' },
    { name: 'Ampara', postalCode: '91710', province: 'Uva Province' },
    { name: 'Paragahadeniya', postalCode: '91730', province: 'Uva Province' },
    { name: 'Ethimale', postalCode: '91750', province: 'Uva Province' },
    { name: 'Diyabalanewa', postalCode: '91770', province: 'Uva Province' },
    { name: 'Siwalakulama', postalCode: '91790', province: 'Uva Province' },
    { name: 'Madampe', postalCode: '91810', province: 'Uva Province' },
    { name: 'Yakkalamulla', postalCode: '91830', province: 'Uva Province' },
    { name: 'Mahawelgama', postalCode: '91850', province: 'Uva Province' },
    { name: 'Kotagala', postalCode: '91870', province: 'Uva Province' },
    { name: 'Meegahakiwula', postalCode: '91890', province: 'Uva Province' },
    { name: 'Kumbalgamuwa', postalCode: '91910', province: 'Uva Province' },
    { name: 'Kobeigane', postalCode: '91930', province: 'Uva Province' },
    { name: 'Divulapelessa', postalCode: '91950', province: 'Uva Province' },
    { name: 'Kumbalwela', postalCode: '91970', province: 'Uva Province' },
    { name: 'Madagama', postalCode: '91990', province: 'Uva Province' },
  ],

  SRI_LANKAN_PROVINCES: [
    'Western Province',
    'Central Province',
    'Southern Province',
    'Northern Province',
    'Eastern Province',
    'North Western Province',
    'North Central Province',
    'Uva Province',
    'Sabaragamuwa Province',
  ],
  /**
   * Sports Categories Hierarchy
   * Sports Category > Sports > Sports Items > Brands
   */
  SPORTS_CATEGORIES: {
    'Ball Sports': {
      icon: '⚽',
      description: 'Equipment for ball-based sports',
      slug: 'ball-sports',
      sports: {
        Cricket: {
          description: 'Cricket bats, balls, protective gear, and accessories',
          slug: 'cricket',
          items: {
            Bats: {
              description: 'Premium cricket bats for all levels',
              slug: 'bats',
              brands: [
                { name: 'Gray-Nicolls', description: 'Premium cricket equipment since 1855' },
                { name: 'Leverage', description: 'Advanced bowling machines' },
              ],
              image: '/cricket.avif',
              link: '/products?category=cricket&item=bats',
            },
            Balls: {
              description: 'Match and training cricket balls',
              slug: 'balls',
              brands: [
                { name: 'Gray-Nicolls', description: 'International standard cricket balls' },
              ],
              image: '/cricket.avif',
              link: '/products?category=cricket&item=balls',
            },
            Protective: {
              description: 'Pads, gloves, helmets, and guards',
              slug: 'protective',
              brands: [{ name: 'Aero', description: 'Professional protective gear' }],
              image: '/cricket.avif',
              link: '/products?category=cricket&item=protective',
            },
          },
        },
        Rugby: {
          description: 'Rugby balls, protective gear, and accessories',
          items: {
            Balls: {
              description: 'Official match and training rugby balls',
              brands: [{ name: 'Gilbert', description: 'Official Rugby World Cup supplier' }],
              image: '/rugby.avif',
              link: '/products?category=rugby&item=balls',
            },
            Protective: {
              description: 'Headguards, pads, and team accessories',
              brands: [{ name: 'Gilbert', description: 'Advanced rugby protective gear' }],
              image: '/rugby.avif',
              link: '/products?category=rugby&item=protective',
            },
          },
        },
        Basketball: {
          description: 'Basketballs and accessories',
          items: {
            Balls: {
              description: 'Olympic-grade basketballs',
              brands: [{ name: 'Molten', description: 'Official Olympic basketball supplier' }],
              image: '/basketball.avif',
              link: '/products?category=basketball&item=balls',
            },
          },
        },
        Volleyball: {
          description: 'Championship volleyballs and accessories',
          items: {
            Balls: {
              description: 'Professional volleyballs',
              brands: [{ name: 'Molten', description: 'Championship quality volleyballs' }],
              image: '/volleyball.avif',
              link: '/products?category=volleyball&item=balls',
            },
          },
        },
      },
    },
    'Racquet Sports': {
      icon: '🎾',
      description: 'Professional racquet equipment',
      slug: 'racquet-sports',
      sports: {
        Tennis: {
          description: 'Tennis rackets, strings, and accessories',
          slug: 'tennis',
          items: {
            Rackets: {
              description: 'Tournament-grade tennis rackets',
              slug: 'rackets',
              brands: [
                { name: 'Babolat', description: 'Roland-Garros official partner' },
                { name: 'Ashaway', description: 'Premium tennis strings since 1824' },
              ],
              image: '/tennis.avif',
              link: '/products?category=tennis&item=rackets',
            },
            Strings: {
              description: 'High-performance tennis strings',
              slug: 'strings',
              brands: [{ name: 'Ashaway', description: 'Professional tennis strings' }],
              image: '/tennis.avif',
              link: '/products?category=tennis&item=strings',
            },
          },
        },
        Badminton: {
          description: 'Badminton rackets, strings, and accessories',
          slug: 'badminton',
          items: {
            Rackets: {
              description: 'Professional badminton rackets',
              slug: 'rackets',
              brands: [
                { name: 'Babolat', description: 'Professional badminton equipment' },
                { name: 'Ashaway', description: 'High-performance badminton strings' },
              ],
              image: '/badminton.avif',
              link: '/products?category=badminton&item=rackets',
            },
            Strings: {
              description: 'Competitive badminton strings',
              slug: 'strings',
              brands: [{ name: 'Ashaway', description: 'High-performance badminton strings' }],
              image: '/badminton.avif',
              link: '/products?category=badminton&item=strings',
            },
          },
        },
        Squash: {
          description: 'Squash rackets and strings',
          slug: 'squash',
          items: {
            Rackets: {
              description: 'Precision squash rackets',
              slug: 'rackets',
              brands: [
                { name: 'Ashaway', description: 'Precision squash strings for power and control' },
              ],
              image: '/squash.avif',
              link: '/products?category=squash&item=rackets',
            },
          },
        },
      },
    },
    'Field Sports': {
      icon: '🏑',
      description: 'Field and outdoor sports gear',
      slug: 'field-sports',
      sports: {
        Hockey: {
          description: 'Hockey sticks, balls, and protective gear',
          slug: 'hockey',
          items: {
            Sticks: {
              description: 'Olympic standard hockey sticks',
              slug: 'sticks',
              brands: [{ name: 'Grays', description: 'Olympic standard hockey equipment' }],
              image: '/hockey.avif',
              link: '/products?category=hockey&item=sticks',
            },
            Balls: {
              description: 'Competition and training hockey balls',
              slug: 'balls',
              brands: [{ name: 'Grays', description: 'International standard hockey balls' }],
              image: '/hockey.avif',
              link: '/products?category=hockey&item=balls',
            },
          },
        },
        Football: {
          description: 'Football training and match equipment',
          slug: 'football',
          items: {
            Goals: {
              description: 'Pop-up training goals',
              slug: 'goals',
              brands: [{ name: 'Pugg', description: 'Original pop-up training goals' }],
              image: '/football.avif',
              link: '/products?category=football&item=goals',
            },
          },
        },
      },
    },
    Training: {
      icon: '🏋️',
      description: 'Multi-sport training equipment',
      slug: 'training',
      sports: {
        'Multi-Sport Training': {
          description: 'Comprehensive training solutions',
          slug: 'multi-sport-training',
          items: {
            Equipment: {
              description: 'Agility, strength, and team training gear',
              slug: 'equipment',
              brands: [{ name: 'Fusion', description: 'Comprehensive training solutions' }],
              image: '/training.avif',
              link: '/products?category=training&item=equipment',
            },
          },
        },
      },
    },
  },
  'Ball Sports': {
    icon: '⚽',
    description: 'Equipment for ball-based sports',
    sports: {
      Cricket: {
        description: 'Cricket bats, balls, protective gear, and accessories',
        items: {
          Bats: {
            description: 'Premium cricket bats for all levels',
            brands: [
              { name: 'Gray-Nicolls', description: 'Premium cricket equipment since 1855' },
              { name: 'Leverage', description: 'Advanced bowling machines' },
            ],
            image: '/cricket.avif',
            link: '/products?category=cricket&item=bats',
          },
          Balls: {
            description: 'Match and training cricket balls',
            brands: [{ name: 'Gray-Nicolls', description: 'International standard cricket balls' }],
            image: '/cricket.avif',
            link: '/products?category=cricket&item=balls',
          },
          Protective: {
            description: 'Pads, gloves, helmets, and guards',
            brands: [{ name: 'Aero', description: 'Professional protective gear' }],
            image: '/cricket.avif',
            link: '/products?category=cricket&item=protective',
          },
        },
      },
      Rugby: {
        description: 'Rugby balls, protective gear, and accessories',
        items: {
          Balls: {
            description: 'Official match and training rugby balls',
            brands: [{ name: 'Gilbert', description: 'Official Rugby World Cup supplier' }],
            image: '/rugby.avif',
            link: '/products?category=rugby&item=balls',
          },
          Protective: {
            description: 'Headguards, pads, and team accessories',
            brands: [{ name: 'Gilbert', description: 'Advanced rugby protective gear' }],
            image: '/rugby.avif',
            link: '/products?category=rugby&item=protective',
          },
        },
      },
      Basketball: {
        description: 'Basketballs and accessories',
        items: {
          Balls: {
            description: 'Olympic-grade basketballs',
            brands: [{ name: 'Molten', description: 'Official Olympic basketball supplier' }],
            image: '/basketball.avif',
            link: '/products?category=basketball&item=balls',
          },
        },
      },
      Volleyball: {
        description: 'Championship volleyballs and accessories',
        items: {
          Balls: {
            description: 'Professional volleyballs',
            brands: [{ name: 'Molten', description: 'Championship quality volleyballs' }],
            image: '/volleyball.avif',
            link: '/products?category=volleyball&item=balls',
          },
        },
      },
    },
  },
  'Racquet Sports': {
    icon: '🎾',
    description: 'Professional racquet equipment',
    sports: {
      Tennis: {
        description: 'Tennis rackets, strings, and accessories',
        items: {
          Rackets: {
            description: 'Tournament-grade tennis rackets',
            brands: [
              { name: 'Babolat', description: 'Roland-Garros official partner' },
              { name: 'Ashaway', description: 'Premium tennis strings since 1824' },
            ],
            image: '/tennis.avif',
            link: '/products?category=tennis&item=rackets',
          },
          Strings: {
            description: 'High-performance tennis strings',
            brands: [{ name: 'Ashaway', description: 'Professional tennis strings' }],
            image: '/tennis.avif',
            link: '/products?category=tennis&item=strings',
          },
        },
      },
      Badminton: {
        description: 'Badminton rackets, strings, and accessories',
        items: {
          Rackets: {
            description: 'Professional badminton rackets',
            brands: [
              { name: 'Babolat', description: 'Professional badminton equipment' },
              { name: 'Ashaway', description: 'High-performance badminton strings' },
            ],
            image: '/badminton.avif',
            link: '/products?category=badminton&item=rackets',
          },
          Strings: {
            description: 'Competitive badminton strings',
            brands: [{ name: 'Ashaway', description: 'High-performance badminton strings' }],
            image: '/badminton.avif',
            link: '/products?category=badminton&item=strings',
          },
        },
      },
      Squash: {
        description: 'Squash rackets and strings',
        items: {
          Rackets: {
            description: 'Precision squash rackets',
            brands: [
              { name: 'Ashaway', description: 'Precision squash strings for power and control' },
            ],
            image: '/squash.avif',
            link: '/products?category=squash&item=rackets',
          },
        },
      },
    },
  },
  'Field Sports': {
    icon: '🏑',
    description: 'Field and outdoor sports gear',
    sports: {
      Hockey: {
        description: 'Hockey sticks, balls, and protective gear',
        items: {
          Sticks: {
            description: 'Olympic standard hockey sticks',
            brands: [{ name: 'Grays', description: 'Olympic standard hockey equipment' }],
            image: '/hockey.avif',
            link: '/products?category=hockey&item=sticks',
          },
          Balls: {
            description: 'Competition and training hockey balls',
            brands: [{ name: 'Grays', description: 'International standard hockey balls' }],
            image: '/hockey.avif',
            link: '/products?category=hockey&item=balls',
          },
        },
      },
      Football: {
        description: 'Football training and match equipment',
        items: {
          Goals: {
            description: 'Pop-up training goals',
            brands: [{ name: 'Pugg', description: 'Original pop-up training goals' }],
            image: '/football.avif',
            link: '/products?category=football&item=goals',
          },
        },
      },
    },
  },
  Training: {
    icon: '🏋️',
    description: 'Multi-sport training equipment',
    sports: {
      'Multi-Sport Training': {
        description: 'Comprehensive training solutions',
        items: {
          Equipment: {
            description: 'Agility, strength, and team training gear',
            brands: [{ name: 'Fusion', description: 'Comprehensive training solutions' }],
            image: '/training.avif',
            link: '/products?category=training&item=equipment',
          },
        },
      },
    },
  },
}

export type SportsCategoriesType = {
  [category: string]: {
    icon: string
    description: string
    sports: {
      [sport: string]: {
        description: string
        items: {
          [item: string]: {
            description: string
            brands: Array<{
              name: string
              description: string
            }>
            image: string
            link: string
          }
        }
      }
    }
  }
}

export type SiteConfig = typeof SITE_CONFIG
